### ISSUE TITLE
Replace text into Symbols override

### ISSUE THREAD

**Issue by icona79** [paintedbicycle/sketch-data-faker#11]
It would be nice the have an option to override text into symbols.

My use case is:
I have a big table where I'd love to place fake looks real data. Every row is a collection of symbols (or a symbol with nested symbols).

The idea is to use the text content of the cell as a placeholder for the plugin:

1. The symbol cell text is something like: `internet.email` (note: Not the name of the symbol of layer, but the actual text into it)
2. Run the plugin over the selected symbols
3. The plugin recursively place rando fake data into the cells managing to overyde the original text (`internet.email`) into the actual loaded data.

I hope it makes sense for you :)

**Comment by paintedbicycle** [comment]
Hi @icona79 - if I understand correctly this is already how the plugin works. It works in symbols just fine. However you need to change the name of your layer.  The content is not read by the plugin because it gets replaced and so it’s then gone if the plugin is run a second time. So change your layer names and the plugin should do what you’ve asked. 

If I misunderstood, feel free to reopen

**Comment by icona79** [comment]
I @paintedbicycle I cannot use the text layer name: the convention for the symbols exclude completely I can rename them. I'd love to have some different option in order to manage it, if possible.

When I'm creating an instance of my table cell, I recall a symbol. The symbol text layer name is something like: ↳ Cell Text.
This is because the symbol has to be re usable everywhere, not only in the current table.

When I'm managing to create a new IBANs, this layer should be `finance.iban`, whether if the cell is the account ID it'd be `finance.account`. My problem is that my Cell symbol is everytime the same one with a text layer named `↳ Cell Text`.

Actually, I have a plugin I developed that created for me a table row with the required amount of cells and extra items. The result of that plugin is a document Symbol named Table--row every designer can customize overriding what is possible. In the case of a text layer, just the content. 
The result of it is that we'll have many instances of that row. If I can override the text into the master document symbol with `finance.iban` and then from the instances pass over this plugin
overriding that text it'd be perfect!

**Comment by paintedbicycle** [comment]
Can you tell me if the `manual mode` of my plugin works the way you would like?

Right now there are 2 ways to use the plugin: `Automatic Mode` (with the layer name) and `Manual Mode` where you do not have to change the layer name. There is only ~7 pieces of data available for the `Manual Mode` but it is possible I could increase this. 

Can you try to see if this works? You would need to select the text layer inside the symbol (using the layer list on the left) and then with my plugin, set the Data Source to be a type of data. Just test it with any data. Then, tell me if this works. If yes, I may add more data options.

My plugin will never be able to read the `content` of the layer because once my plugin changes the content, it will never again be possible for the plugin to know what type of data you want there again in the future. This is because my plugin changes the data in the content of the layer. So, once it's changed from `person.email` to `jdoe@example.org`, it is no longer possible to know if it was `person.email` before. The plugin is designed for offer the ability to duplicate the layer to get different data by refreshing the data. This way the data is unique to each layer. But it cannot do this if it loses the information on what type of data you requested in the first place.

However, as mention, maybe the `Manual Mode` will work. Let me know.
