### ISSUE TITLE
Customize manual options in the sketch data menu

### ISSUE THREAD

**Issue by wvaughan** [paintedbicycle/sketch-data-faker#15]
This is a great plugin! I'd love to be able to customize the options that are shown in the override menu.
![image](https://user-images.githubusercontent.com/757845/87728141-6f046b00-c790-11ea-99ff-a134bb3215f5.png)

**Comment by paintedbicycle** [comment]
Hey @wvaughan thank you!

Yes, I agree that it's not ideal to only offer a few options in the "quick way" of using the plugin. I want to offer all options with just one click and not having to change the layer. The full way to fix this is currently blocked by a limitation in the Sketch plugin ecosystem. I've opened a bug here: https://github.com/sketch-hq/SketchAPI/issues/296

If that gets fixed, I can make all options behave like these 8 and that would be my preferred way of doing this (rather than building a customizing interface).

Have you explored using the `layerName` option where you can access all the other data?

Going to close this for now as I'd rather fix it "the right way", but I'm currently blocked but I may open it again if other ideas come up. 

Thanks for using my plugin!
