### ISSUE TITLE
List all Faker options

### ISSUE THREAD

**Issue by inlinecoder** [paintedbicycle/sketch-data-faker#4]
Currently we have a very limited set of 7 options + 'Auto', but that would be great if all Faker options were listed, so we don't have to type them manually, but rather select existing ones and that makes usage of `sketch-data-faker` less error-prone and doesn't force us to read documentation.

**Comment by paintedbicycle** [comment]
Hey @inlinecoder - while I understand the sentiment, I don't think _listing all_ in the **Data Feeds** menu would be viable. The menu would be 130+ items long! And I'm looking at adding even more APIs from other sources.

However, I have been considering different two ideas to solve this problem:
1.  Some sort of `autocomplete` that would allow you to insert a layer name from a popup accessible from the _plugin_ menu (not the data feeds menu)
2. Including a _Sketch library_ with basic texts and other layer patterns for common things like titles, products, blog posts, etc that you could hook up and insert into your Sketch document and it'd have the layers already named properly when you import them from the library

Not sure where I'll go with this just yet, but anyway thanks for the feedback, I'll keep it in mind for when I'm looking what to do next.

**Comment by inlinecoder** [comment]
@paintedbicycle , thanks for getting back to me.

By writing 'listing all options' I didn't mean like literally listing them all one by one, I meant to start a conversation towards finding a consensus. Nonetheless, having the nested drop-downs in Sketch would definitely simplify that.

+1 for Autocomplete — might be a good thing to use daily.

**Comment by paintedbicycle** [comment]
Hi @inlinecoder - I just pushed version 0.2.0 which includes a new plugin menu.

We now have:

1. The Data Menu (as before)
2. The Plugin Menu (new)

In the Plugin Menu (i.e. the menu called "Plugins" in Sketch), I've put an entry in there for Sketch Data Faker that shows all available data sources. Hope this helps.

Additionally, If you click on one of those data sources (while a layer is (or layers are) selected), it will replace the layer name(s) for you, so you don't have to. This should reduce typos and having to go lookup the data in the table so often.

Due to a limitation in the Sketch API (issue here: https://github.com/BohemianCoding/SketchAPI/issues/296), I can't take the extra step of also hooking up the "Data Feed" on that layer to be "Automatic (Layer Name)" - so once you use this plugin menu item to help you set the layer name(s), you then go to the Data Menu to set the Data Source to "Automatic (Layer Name)" just like always. 

_As a tip, you can set all the layer names on all your layers (even if they are different) and then once, at the end, select all layers (even if they are different) and set the "Data Feed" to be "Automatic (Layer Name)" and everything will refresh and work as expected._

If the API adds the ability to do both steps in one I'll update the plugin to support that too.

Since I'm now listing all faker options as per this issue, I'm closing it. Please let me know what you think.

**Comment by inlinecoder** [comment]
@paintedbicycle thank you man for getting back to me and taking your time to do stuff and writing here again. Highly appreciated. 👍

Sorry for the late response tho.

**Comment by inlinecoder** [comment]
@paintedbicycle I personally like the new approach much more, as I don't have to memorize everything, but just select an option I want.
