### ISSUE TITLE
Add localised data formatting

### ISSUE THREAD

**Issue by ErikFontanel** [paintedbicycle/sketch-data-faker#6]
Great work on this plugin, something like this has been missing for a long time. It'd be great if the data would be formatted according to the locale as well. ie. a phone number follows the US format (555) 012 3123 vs. +31 1 23 45 67 8 and $ 2,399.40 vs € 1.323,30.

I'm not too familiar with faker.js but I suspect we need to add another tool like http://numeraljs.com/ to format the faker data. 

If I find some time next week, I'll look into this.

Slightly related: saving a default locale as a setting would be handy too.

**Comment by paintedbicycle** [comment]
Hi @ErikFontanel thank you and yes, I agree with you that those formats should match locale. I assumed `Faker.js` would do that.

Now, I want to integrate this request, but I am going to hold off for a little bit until I can sort out some questions I have. I have several issues right now that hold me back from doing this. 

These are:

1. I think this ticket is better suited upstream (on the `Faker.js` project itself) as I am already asking `Faker.js` to provide me their data in a specific locale. They do already have locale support built-in and are the ones supplying the data. So it's an issue on their end if they are not sending me the correctly formatted data. It seems silly to have to re-format their data in my project based on that locale.

In fact, there are some open tickets over there around locales:
https://github.com/Marak/faker.js/issues/753
https://github.com/Marak/faker.js/issues/486
https://github.com/Marak/faker.js/issues/752
https://github.com/Marak/faker.js/issues/747
https://github.com/Marak/faker.js/issues/598

2. Adding extra dependencies. I don't want to get too far into dependencies in this project which add weight and maintenance. But on top of weight and maintenance, looking specifically the `numeral.js` project, it doesn't seem to be well supported any more (over 2 years since the last change and over a hundred open issues). Even if we find another project, the weight and maintenance issues remain.
3. It's also going to be messy to catch the data coming back and supply it to these plugins inside `Sketch Data Faker`. If they give us a `time`, or a `currency` or a `tel`, we have to know what we are going to get and use the specific methods on it. That's a lot of extra logic to maintain.
4. Last, but perhaps most important - I am hoping to add other data sources in the near future to `Sketch Data Faker`. In these other data sources, there may be better formatting options, which could help here. But even if not, I wouldn't want us to go too far down the path of formatting logic until I can figure out a way to get `Sketch Data Faker` to use multiple data APIs. Then, if we need more formatting, we can apply it to everything, not just `Faker`.

As to your second request - `Default Locales`, I agree here too. In the original ticket (https://github.com/paintedbicycle/sketch-data-faker/issues/5#issuecomment-466641080), I thought about this. I think you're right and I'm going to open a new ticket to track it. You can see it here: https://github.com/paintedbicycle/sketch-data-faker/issues/7

**Comment by ErikFontanel** [comment]
Hey Paul,

Thanks for the thought out reply and concerns on maintainability, definitely something people can learn from :)

1. Agreed, I was surprised myself these issues were not resolved in faker.js already. Considering `faker.js` seems pretty active, it's a fair bet to rely on the upstream to get this fixed.
2. True. I'm not experienced enough in the locale side of JS, but natively JS already supports quite some formatting functionality. Ie. [Number.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString). Perhaps that's a direction to explore. Although I'm sure that will be it's own can of worms haha.
3. & 4. Gotcha. I'm surprised there has been such a lack of data supplier plugins since the release of Sketch 52, so it's assuring to read that you have this on your radar.

For now I think I'll just use some localised txt files as a fallback for stuff like the phone numbers.

**Comment by paintedbicycle** [comment]
Closing this as wontfix for now, but open to reopening it once I know more about other data sources I add and if they need a formatting layer.
