### ISSUE TITLE
Auto feature (renaming layer) doesn't work with Symbols

### ISSUE THREAD

**Issue by madysondesigns** [paintedbicycle/sketch-data-faker#9]
Hello-

I just downloaded and installed this plugin and I am experiencing the same issue as #1 on the latest version. I rolled back to 0.1.9 and I was able to use the naming feature successfully, but upgrading to the latest breaks it again. 

Screenshot of error: 
<img width="442" alt="Screenshot 2019-06-04 15 32 56" src="https://user-images.githubusercontent.com/1100018/58908242-0d915200-86de-11e9-9111-b77304508f5b.png">
In my file, 'list' is an instance of a symbol which has two Faker named layers.

**Comment by paintedbicycle** [comment]
Hi @madysondesigns - "list" isn't one of the names of layers that you can use when using the "Auto" feature. It has to be one of the layer names in the Readme. For example "name.firstName".

**Comment by madysondesigns** [comment]
'list' is the name of the symbol instance. The symbol master contains text layers using the proper Faker names (name.firstName and name.lastName). I'm trying to use auto data in the overrides panel of the instance 'list'. 

I'm not sure what you mean by complex symbols, what makes a symbol complex?

**Comment by paintedbicycle** [comment]
Ok I will try to take a look and recreate what you have.

By complex I simply meant that sketch data faker only applies on text layers. Those layers can be symbols or inside symbols (as you have). The popup image you sent implies to me that the plugin tried to run on the symbol, rather than on the text layers inside the symbol.

I recently made a change where I now support symbols from libraries and therefore apply the plugin slightly differently than I did. It may be the cause of it.

I'll review Friday or Saturday if I can

**Comment by madysondesigns** [comment]
The text layers I'm trying to fill are in the root of the symbol, not grouped or anything. There are some other layers in groups but based on your comment, it seems like it should work. 

If a sample sketch would still be helpful, let me know.

**Comment by paintedbicycle** [comment]
Got it, thanks @madysondesigns. I think I know what it is - a recent change I made that now allows Sketch Data Faker to work on symbols imported from Library files - so I'll take a look and report back if I need a sample sketch file

**Comment by paintedbicycle** [comment]
Hi @madysondesigns thank you for your patience.

I've pushed version 0.6.1 that should work again with Symbols. I have tested it with both basic and grouped symbols that contain several text layers and it works well.

Please test it and let me know what you think.

Note that I had to undo some work on making it work with imported libraries. There seems to be an issue here that I haven't been able to work through. It's inconsistent.

Either way, this issue was about Symbols and it should be solved. Feel free to re-open if not.

**Comment by paintedbicycle** [comment]
I have now pushed version 0.7.0 which brings back the ability to supply data to symbols imported from libraries as well!

It should now work in all cases. Please let me know if you find anywhere this plugin doesn't work
